FROM mcr.microsoft.com/dotnet/sdk:9.0

# Install vsdbg for debugging
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./

EXPOSE 5142
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5142"]
