services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./Frontend:/app:z
      - /app/node_modules
    environment:
      - VITE_API_TARGET=http://backend:5142
      - VITE_PORT=5173

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    ports:
      - "5142:5142"
    restart: always
    volumes:
      - ./Backend:/app:z
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5142
